@baseUrl = http://localhost:7000
@authToken = insert_your_token_here

### Create movie: The Shawshank Redemption
POST {{baseUrl}}/movies
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "The Shawshank Redemption",
    "description": "A prominent banker is wrongly convicted of murder and sentenced to life imprisonment at the Shawshank prison. Over the years, he forms a deep friendship with a fellow inmate and finds ways to retain his humanity and hope.",
    "duration": 142,
    "ageRating": "R"
}
